config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :movies do
    resources :reviews
    resources :favorites
  end

  resources :users
  get "signup" => "users#new"
  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"

  resources :genres

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
   <p>
    Copyright &copy; 2005-<%= Time.now.year %>
    <%= link_to 'The Pragmatic Studio','https://pragmaticstudio.com' %>
  </p>
  <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav>
      <%= link_to image_tag('logo.png'), root_path %>
      <ul class="left">
        <li><%= nav_link_to 'Released', movies_path %></li>
        <li><%= nav_link_to 'Recent', filtered_movies_path(:recent) %></li>
        <li><%= nav_link_to 'Upcoming', filtered_movies_path(:upcoming) %></li>
        <li><%= nav_link_to 'Hits', filtered_movies_path(:hits) %></li>
        <li><%= nav_link_to 'Flops', filtered_movies_path(:flops) %></li>
      </ul>
      <ul class="right">
        <% if current_user %>
          <li><%= link_to current_user.name, current_user %></li>
          <li>
            <%= link_to "Account Settings", edit_user_path(current_user) %>
          </li>
          <li>
            <%= link_to "Sign Out", session_path, method: :delete, class: "button" %>
          </li>
        <% else %>
          <li><%= link_to 'Sign in', signin_path, class: "button" %></li>
          <li><%= link_to 'Sign up', signup_path, class: "button" %></li>
        <% end %>
      </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super-Heroic Flix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>